seed: 1337
log_level: "INFO"
log_format: "%(asctime)s - %(levelname)s - %(message)s"
data:
  local_data_path: "data"
  file_name: "train"
  extension: ".csv"
preprocessing:
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
model:
  num_cols: ["x1", "x2", "x4", "x5"]
  cat_cols: ["x3", "x6", "x7"]
  feature_col: 'x'
  target_col: "y"
  batch_size: 25
  learning_rate: 0.001
  hidden_dim: 5
  num_workers: 0
  max_epochs: 10000
  decision_metric: "test_mcc"
  model_type: 'sklearn.linear_model.LogisticRegression'
