seed: 007
log_level: "INFO"
log_format: "%(asctime)s - %(levelname)s - %(message)s"
data:
  local_data_path: "data"
  file_name: "iris"
  extension: ".parquet"
preprocessing:
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
model:
  feature_cols: ["sepal_length_cm", "sepal_width_cm", "petal_length_cm", "petal_width_cm"]
  target_col: "target"
  batch_size: 32
  learning_rate: 0.01
  hidden_dim: 5
  num_workers: 0
  max_epochs: 1000
  decision_metric: "test_mcc"
